apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-mime-types
  namespace: ingress-basic
data:
  mime.types: |
    types {
      text/html                             html htm shtml;
      text/css                              css;
      application/javascript                js;
      text/xml                              xml;
      image/gif                             gif;
      image/jpeg                            jpeg jpg;
      application/json                      json;
      image/png                             png;
      image/svg+xml                         svg svgz;
      image/webp                            webp;
      image/x-icon                          ico;
      font/woff                             woff;
      font/woff2                            woff2;
      application/zip                       zip;
      text/plain                            txt;
    } 