FROM nginx:alpine
WORKDIR /usr/share/nginx/html

# Copy built assets
COPY dist/ .

# Copy nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy env-config.js
COPY public/env-config.js ./env-config.js

# Expose port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
