version: '3.8'

services:

  user-service:
    build: ./user-service
    ports:
      - "8082:8080"
    container_name: user-service

  content-service:
    build: ./content-service
    ports:
      - "8082:8082"
    container_name: content-service

  media-service:
    build: ./media-service
    ports:
      - "8083:8083"
    container_name: media-service

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend
    depends_on:
      - user-service
      - content-service
      - media-service
