apiVersion: v1
kind: Service
metadata:
  name: frontend-direct
  namespace: microservices
spec:
  selector:
    app: frontend-direct
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-direct
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-direct
  template:
    metadata:
      labels:
        app: frontend-direct
    spec:
      containers:
      - name: frontend
        image: pngbanks/frontend:prod
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: env-config
          mountPath: /usr/share/nginx/html/env-config.js
          subPath: env-config.js
      volumes:
      - name: nginx-conf
        configMap:
          name: frontend-nginx-conf
      - name: env-config
        configMap:
          name: frontend-env-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-conf
  namespace: microservices
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;

        # MIME types
        include /etc/nginx/mime.types;
        types {
            application/javascript js;
            text/css css;
        }

        # Serve static files
        location / {
            try_files $uri $uri/ /index.html;
            add_header 'Access-Control-Allow-Origin' '*';
        }

        # JavaScript files - explicitly set content type
        location ~* \.js$ {
            add_header Content-Type application/javascript;
            try_files $uri =404;
        }

        # CSS files - explicitly set content type
        location ~* \.css$ {
            add_header Content-Type text/css;
            try_files $uri =404;
        }

        # Asset files
        location /assets/ {
            try_files $uri =404;
        }

        # Handle API requests
        location /api/ {
            proxy_pass http://api-gateway;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-env-config
  namespace: microservices
data:
  env-config.js: |
    // This file is generated at build time and injected into the static HTML
    window.ENV = {
      API_URL: '/api',
      AUTH0_DOMAIN: 'dev-i9j8l4xe.us.auth0.com',
      AUTH0_CLIENT_ID: 'JBfJJE07F7yrWTPq7nZ04WO4XdqzPvOa',
      AUTH0_AUDIENCE: 'https://api.inspira.com',
      AUTH0_REDIRECT_URI: window.location.origin,
      ENV: 'production'
    };
    console.log('Environment config loaded:', window.ENV);
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-direct-ingress
  namespace: microservices
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-direct
            port:
              number: 80 