spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /users/$\{segment}
        - id: content-service
          uri: ${CONTENT_SERVICE_URL}
          predicates:
            - Path=/api/content/**
          filters:
            - RewritePath=/api/content/(?<segment>.*), /content/$\{segment}
        - id: media-service
          uri: ${MEDIA_SERVICE_URL}
          predicates:
            - Path=/api/media/**
          filters:
            - RewritePath=/api/media/(?<segment>.*), /media/$\{segment}
        - id: user-service-health
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/api/health
          filters:
            - RewritePath=/api/health, /health
        - id: content-service-health
          uri: ${CONTENT_SERVICE_URL}
          predicates:
            - Path=/api/content-health
          filters:
            - RewritePath=/api/content-health, /health
        - id: media-service-health
          uri: ${MEDIA_SERVICE_URL}
          predicates:
            - Path=/api/media-health
          filters:
            - RewritePath=/api/media-health, /health

server:
  port: 8080 