image: docker:20.10.16

services:
  - name: docker:20.10.16-dind
    alias: docker

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  IMAGE_NAME: pngbanks/auth-service
  KUBECONFIG: "/builds/$CI_PROJECT_PATH/kubeconfig"
  KUBE_NAMESPACE: staging

stages:
  - build_and_push
  - deploy

build_and_push:
  stage: build_and_push
  script:
    - echo "Plamski@1960" | docker login -u "pngbanks" --password-stdin
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHA .
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHA $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME:latest

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - echo "$KUBECONFIG_DATA" | base64 -d > $KUBECONFIG
    - kubectl apply -f content-service/k8s/config.yaml --namespace=$KUBE_NAMESPACE
