apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-service
  template:
    metadata:
      labels:
        app: content-service
    spec:
      containers:
      - name: content-service
        image: ghcr.io/plamennyagolov/inspira/content-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 150m
            memory: 256Mi
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-content:5432/content_db"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-content-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-content-secret
              key: password
        volumeMounts:
        - name: health-endpoint
          mountPath: /usr/share/nginx/html/health.html
        env:
        - name: POSTGRES_HOST
          value: postgres-content
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: content
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: content-db-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: content-db-password
        - name: MINIO_ENDPOINT
          value: http://minio:9000
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: storage-secrets
              key: storage-account-name
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: storage-secrets
              key: storage-account-key
        readinessProbe:
          httpGet:
            path: /health.html
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health.html
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: health-endpoint
        configMap:
          name: content-service-health
          items:
          - key: health.html
            path: health.html
---
apiVersion: v1
kind: Service
metadata:
  name: content-service
  namespace: microservices
  labels:
    app: content-service
    monitoring: "true"
spec:
  selector:
    app: content-service
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP 