apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: pngbanks/frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "/api"
        - name: AUTH0_AUDIENCE
          value: "https://api.inspira.com"
        - name: AUTH0_REDIRECT_URI
          value: "https://4.156.37.48/"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: microservices
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP 