name: Azure K8s Deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write

env:
  NAMESPACE: staging
  AZURE_RESOURCE_GROUP: inspira-project
  AKS_CLUSTER_NAME: inspira-aks
  AZURE_CLIENT_ID: "23bbcc2b-04c2-4589-84e3-1e1254b698d8"
  AZURE_TENANT_ID: "c66b6765-b794-4a2b-84ed-845b341c086a"
  AZURE_SUBSCRIPTION_ID: "0e46a8f2-8dd8-4c4e-841f-94a20add816d"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'
      
      - name: Create namespace
        run: |
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -
      
      - name: Deploy to AKS
        uses: azure/k8s-deploy@v4
        with:
          namespace: ${{ env.NAMESPACE }}
          manifests: |
            k8s/overlays/staging/frontend-deployment.yaml
            k8s/overlays/staging/nginx-config.yaml
          strategy: none 