name: Azure K8s Deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write

env:
  NAMESPACE: staging
  AZURE_RESOURCE_GROUP: inspira-project
  AKS_CLUSTER_NAME: inspira-aks

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Debug information
        run: |
          echo "GitHub repository: ${{ github.repository }}"
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub actor: ${{ github.actor }}"
      
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'
      
      - name: Create namespace
        run: |
          echo "Creating namespace: ${{ env.NAMESPACE }}"
          kubectl create namespace ${{ env.NAMESPACE }} || true
          kubectl get namespace ${{ env.NAMESPACE }}
      
      - name: Apply namespace.yaml first
        run: |
          kubectl apply -f k8s/overlays/staging/namespace.yaml
          
      - name: Deploy to AKS
        run: |
          echo "Deploying frontend and nginx config..."
          kubectl apply -f k8s/overlays/staging/frontend-deployment.yaml
          kubectl apply -f k8s/overlays/staging/nginx-config.yaml
          
          echo "Waiting for deployment to complete..."
          kubectl rollout status deployment/frontend -n ${{ env.NAMESPACE }} --timeout=300s 