name: GitHub Container Registry Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/frontend:latest
            ${{ env.REGISTRY }}/${{ env.OWNER }}/frontend:${{ steps.meta.outputs.sha_short }}
      
      - name: Build and push api-gateway image
        uses: docker/build-push-action@v4
        with:
          context: ./api-gateway
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/api-gateway:latest
            ${{ env.REGISTRY }}/${{ env.OWNER }}/api-gateway:${{ steps.meta.outputs.sha_short }}
      
      - name: Build and push user-service image
        uses: docker/build-push-action@v4
        with:
          context: ./user-service
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/user-service:latest
            ${{ env.REGISTRY }}/${{ env.OWNER }}/user-service:${{ steps.meta.outputs.sha_short }}
      
      - name: Build and push content-service image
        uses: docker/build-push-action@v4
        with:
          context: ./content-service
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/content-service:latest
            ${{ env.REGISTRY }}/${{ env.OWNER }}/content-service:${{ steps.meta.outputs.sha_short }}
      
      - name: Build and push media-service image
        uses: docker/build-push-action@v4
        with:
          context: ./media-service
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/media-service:latest
            ${{ env.REGISTRY }}/${{ env.OWNER }}/media-service:${{ steps.meta.outputs.sha_short }}
      
      - name: Summary
        run: |
          echo "## Successfully built and pushed images to GitHub Container Registry" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Service | Image URL |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| Frontend | ${{ env.REGISTRY }}/${{ env.OWNER }}/frontend:${{ steps.meta.outputs.sha_short }} |" >> $GITHUB_STEP_SUMMARY
          echo "| API Gateway | ${{ env.REGISTRY }}/${{ env.OWNER }}/api-gateway:${{ steps.meta.outputs.sha_short }} |" >> $GITHUB_STEP_SUMMARY
          echo "| User Service | ${{ env.REGISTRY }}/${{ env.OWNER }}/user-service:${{ steps.meta.outputs.sha_short }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Content Service | ${{ env.REGISTRY }}/${{ env.OWNER }}/content-service:${{ steps.meta.outputs.sha_short }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Media Service | ${{ env.REGISTRY }}/${{ env.OWNER }}/media-service:${{ steps.meta.outputs.sha_short }} |" >> $GITHUB_STEP_SUMMARY 